DATA:
  data_root: dataset/data/replica_split
  data_root_2d_fused_feature: data/replica_multiview_openseg
  feature_2d_extractor: lseg
  voxel_size: 0.02
  input_color: False
  use_shm: False
  exp_dir: "./experiments/openscene/replica_split"
  use_augmentations: True
  
TEST:
  split: 'all'
  labelset: replica #matterport
  prompt_eng: True
  mark_no_feature_to_unknown: True
  feature_type: 'distill' # 'distill' | 'fusion' | 'ensemble'
  save_feature_as_numpy: False
  eval_iou: False
  vis_input: False
  vis_pred: False
  vis_gt: False
  test_workers: 0
  test_gpu: [0]
  test_batch_size: 1
  model_path: 'https://cvg-data.inf.ethz.ch/openscene/models/matterport_lseg.pth.tar'
  save_folder:
  test_repeats: 1
  arch_3d: MinkUNet18A
  manual_seed: 3407
  save_feature_as_numpy: true

Distributed:
  dist_url: tcp://127.0.0.1:6787
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0